services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    environment:
      - MONGO_URL=mongodb://mongodb:27017/soul-connection

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
