version: '3'
services:
  myapplication:
    build: .
    ports:
      - "80"
    depends_on:
      - db

  db:
    image: mongo:7.0.14
    ports:
      - "27017:27017"
    volumes:
      - type: bind
        source: ./data
        target: /data/db
